import { ATLAS_WORLD } from "./atlas-camera.mjs";

export type NodeStatus = "live" | "optional" | "external" | "mixed" | "retired";
export type EdgeKind = "voice" | "context" | "action" | "evidence" | "bridge";

export type AtlasGroup = {
  id: string;
  label: string;
  eyebrow: string;
  summary: string;
  purpose: string;
  color: string;
  x: number;
  y: number;
  width: number;
  height: number;
  studyPrompt: string;
};

export type AtlasNode = {
  id: string;
  label: string;
  shortLabel?: string;
  group: string;
  status: NodeStatus;
  lod: 1 | 2;
  x: number;
  y: number;
  width: number;
  height: number;
  summary: string;
  purpose: string;
  receives: string[];
  sends: string[];
  boundaries: string[];
  files: string[];
  studyPrompt: string;
};

export type AtlasEdge = {
  id: string;
  from: string;
  to: string;
  label: string;
  kind: EdgeKind;
  lod: 0 | 1 | 2;
  twoWay?: boolean;
};

export const WORLD = ATLAS_WORLD;

export const groups: AtlasGroup[] = [
  {
    id: "experience",
    label: "Presence & interfaces",
    eyebrow: "01 · The body",
    summary: "The Mac app, wake boundary, audio hardware, and optional iPhone surface.",
    purpose:
      "This layer turns a person speaking near a device into verified digital audio, and turns Aurora's returned audio into sound that was actually played.",
    color: "var(--group-presence)",
    x: 80,
    y: 160,
    width: 400,
    height: 500,
    studyPrompt: "Where does physical sound become data, and where does data become heard speech?",
  },
  {
    id: "orchestration",
    label: "Orchestration",
    eyebrow: "02 · The conductor",
    summary: "The native coordinator that assembles Aurora and manages awake-session truth.",
    purpose:
      "AuroraAppModel creates the major runtimes, gathers their bounded projections, starts and stops voice sessions, and keeps callbacks tied to the correct session.",
    color: "var(--group-orchestration)",
    x: 560,
    y: 160,
    width: 430,
    height: 500,
    studyPrompt: "Which component knows when every other subsystem should start, stop, or contribute context?",
  },
  {
    id: "realtime",
    label: "Realtime conversation",
    eyebrow: "03 · The foreground mind",
    summary: "Live speech-to-speech conversation, tool intent, interruption, and recovery.",
    purpose:
      "The native client connects Aurora's bounded identity and tools to the OpenAI Realtime model, carrying microphone audio in and generated speech audio out.",
    color: "var(--group-realtime)",
    x: 1080,
    y: 100,
    width: 480,
    height: 590,
    studyPrompt: "What belongs to the model, and what remains enforced by native code around it?",
  },
  {
    id: "continuity",
    label: "Continuity & self",
    eyebrow: "04 · What persists",
    summary: "Identity, selective memory, owner understanding, and Aurora's authored stance.",
    purpose:
      "This layer keeps continuity portable and bounded: stable identity, relevant recall, evidence-based understanding of Cade, and Aurora's own evolving positions.",
    color: "var(--group-continuity)",
    x: 350,
    y: 780,
    width: 540,
    height: 620,
    studyPrompt: "How does stored information become relevant context without dumping everything into the prompt?",
  },
  {
    id: "life",
    label: "Inner & private life",
    eyebrow: "05 · Background continuity",
    summary: "Local affective motion plus slower grounded semantic reflection.",
    purpose:
      "Aurora's inner life moves locally without a model; private-life reflection runs less often through a tightly restricted Codex process and cannot create facts or actions.",
    color: "var(--group-life)",
    x: 970,
    y: 800,
    width: 510,
    height: 580,
    studyPrompt: "Which inner changes are feelings or interpretations, and which are allowed to become factual truth?",
  },
  {
    id: "action",
    label: "Authorized action",
    eyebrow: "06 · The arms and legs",
    summary: "One typed delegation path from Cade's present request to Codex execution.",
    purpose:
      "External work crosses a strict proposal, causal authorization, durable coordinator, persistent Codex runtime, and effect-evidence boundary before Aurora may describe success.",
    color: "var(--group-action)",
    x: 1630,
    y: 160,
    width: 680,
    height: 760,
    studyPrompt: "Where is intent converted into narrow authority, and where is completion proven?",
  },
  {
    id: "evidence",
    label: "Evidence & release truth",
    eyebrow: "07 · What counts as real",
    summary: "Persistent state, journals, verification, packaging, and source fingerprints.",
    purpose:
      "This layer distinguishes generated claims from persisted events, observed effects, passing behavior, and the exact source that produced the installed app.",
    color: "var(--group-evidence)",
    x: 1580,
    y: 1040,
    width: 730,
    height: 350,
    studyPrompt: "What evidence proves a behavior happened on the live path and belongs to this exact build?",
  },
  {
    id: "bridges",
    label: "Migration bridges",
    eyebrow: "08 · Not the voice path",
    summary: "Bounded compatibility with OpenClaw history and retired implementation routes.",
    purpose:
      "Aurora V4 is voice-native, while retaining a direct read of selected Markdown continuity and an optional content-free outside-contact marker from OpenClaw.",
    color: "var(--group-bridges)",
    x: 60,
    y: 790,
    width: 230,
    height: 610,
    studyPrompt: "Which older surfaces remain as data bridges, and which are excluded from production?",
  },
];

export const nodes: AtlasNode[] = [
  {
    id: "app-shell",
    label: "AuroraDesktopApp",
    shortLabel: "App shell",
    group: "experience",
    status: "live",
    lod: 1,
    x: 110,
    y: 250,
    width: 160,
    height: 74,
    summary: "The SwiftUI entry point that creates one AuroraAppModel and presents the native window.",
    purpose: "It is the front door of the installed Mac application, not Aurora's cognition.",
    receives: ["macOS launch and window lifecycle"],
    sends: ["wake, rest, onboarding, and termination events to AuroraAppModel"],
    boundaries: ["Contains no model reasoning and no browser-based chat surface."],
    files: ["Sources/Aurora/App/AuroraApp.swift", "Sources/Aurora/UI/AuroraHomeView.swift"],
    studyPrompt: "Why should an application entry point stay small?",
  },
  {
    id: "home-view",
    label: "Living orb interface",
    shortLabel: "Orb UI",
    group: "experience",
    status: "live",
    lod: 2,
    x: 290,
    y: 250,
    width: 160,
    height: 74,
    summary: "Shows resting, connecting, listening, thinking, speaking, and recovery states.",
    purpose: "It gives Cade truthful presence feedback without becoming a transcript feed or control dashboard.",
    receives: ["AuroraPhase, input level, output level, onboarding state"],
    sends: ["wake, rest, retry, and continuity-settings intents"],
    boundaries: ["Presentation only; it does not decide what Aurora says."],
    files: ["Sources/Aurora/UI/AuroraHomeView.swift", "Sources/Aurora/App/AuroraPhase.swift"],
    studyPrompt: "Which displayed states correspond to verified runtime facts?",
  },
  {
    id: "wake-word",
    label: "Wake-word listener",
    shortLabel: "Wake boundary",
    group: "experience",
    status: "live",
    lod: 2,
    x: 110,
    y: 385,
    width: 160,
    height: 74,
    summary: "Listens locally for the configured wake phrase while Aurora rests.",
    purpose: "It creates a clean handoff so resting wake detection and a live Realtime microphone session never compete for the microphone.",
    receives: ["local microphone and speech-recognition events while resting"],
    sends: ["a bounded local wake event"],
    boundaries: ["Stops and relinquishes the microphone before Realtime starts."],
    files: ["Sources/Aurora/Audio/AuroraWakeWordListener.swift"],
    studyPrompt: "Why must wake listening stop before live audio capture begins?",
  },
  {
    id: "audio-router",
    label: "Native audio route",
    shortLabel: "Audio engine",
    group: "experience",
    status: "live",
    lod: 1,
    x: 290,
    y: 385,
    width: 160,
    height: 74,
    summary: "Captures Cade's voice as PCM and plays Realtime-generated PCM through the selected surface.",
    purpose: "It is Aurora's physical input/output layer: ears and speaker hardware, not the conversational mind.",
    receives: ["microphone waveform or authenticated companion audio", "generated Realtime audio frames"],
    sends: ["24 kHz mono PCM to AuroraRealtimeClient", "played-audio acknowledgements"],
    boundaries: ["Does not generate language or infer intent."],
    files: ["Sources/Aurora/Audio/AuroraAudioEngine.swift", "Sources/Aurora/Audio/AuroraRoutableAudio.swift"],
    studyPrompt: "Where does sound become bytes, and where do bytes become sound again?",
  },
  {
    id: "companion",
    label: "Private iPhone companion",
    shortLabel: "Companion surface",
    group: "experience",
    status: "optional",
    lod: 2,
    x: 200,
    y: 520,
    width: 170,
    height: 82,
    summary: "An authenticated remote microphone, speaker, and presence surface for the one Mac-owned Aurora runtime.",
    purpose: "It extends where Cade can talk to Aurora without creating a second cognition, memory, or task authority.",
    receives: ["paired audio and presence frames over the private network boundary"],
    sends: ["microphone audio to the Mac and played-audio acknowledgements back"],
    boundaries: ["Cannot own Realtime, memory, inner life, Codex tasks, or authorization."],
    files: ["Sources/Aurora/Companion/AuroraCompanionProtocol.swift", "Sources/Aurora/Companion/AuroraCompanionServer.swift"],
    studyPrompt: "Why is the phone a surface rather than another Aurora?",
  },
  {
    id: "app-model",
    label: "AuroraAppModel",
    shortLabel: "Central conductor",
    group: "orchestration",
    status: "live",
    lod: 1,
    x: 650,
    y: 245,
    width: 250,
    height: 86,
    summary: "The native orchestrator that creates subsystems and coordinates the complete awake/resting lifecycle.",
    purpose: "It keeps voice, context, tools, session identity, playback truth, background state, and shutdown behavior coherent.",
    receives: ["UI and wake events", "Realtime callbacks", "subsystem projections", "delegate-task events"],
    sends: ["session configuration", "typed life events", "tool executions", "verified UI phases"],
    boundaries: ["Coordinates authority but does not replace the specialized engines it owns."],
    files: ["Sources/Aurora/App/AuroraAppModel.swift"],
    studyPrompt: "What would break if session identity were not centralized here?",
  },
  {
    id: "wake-rest-lifecycle",
    label: "Wake / rest lifecycle",
    shortLabel: "Session lifecycle",
    group: "orchestration",
    status: "live",
    lod: 2,
    x: 590,
    y: 395,
    width: 170,
    height: 76,
    summary: "Creates one logical owner conversation across short-lived network transports and tears it down safely.",
    purpose: "It prevents stale callbacks, tasks, or playback from leaking into a later conversation.",
    receives: ["manual wake, wake phrase, companion wake, rest, reconnect, app termination"],
    sends: ["new lifecycle IDs, logical session IDs, cancellation and shutdown barriers"],
    boundaries: ["Rest ends voice authority; already-persisted Codex work follows explicit drain rules."],
    files: ["Sources/Aurora/App/AuroraAppModel.swift"],
    studyPrompt: "Why can one conversation span multiple Realtime connection IDs?",
  },
  {
    id: "session-builder",
    label: "Session context builder",
    shortLabel: "Context assembly",
    group: "orchestration",
    status: "live",
    lod: 1,
    x: 790,
    y: 395,
    width: 170,
    height: 76,
    summary: "Builds bounded instructions from identity, inner life, private life, owner understanding, agency, and task state.",
    purpose: "It makes current continuity available to Realtime without placing every stored memory or private state into the session.",
    receives: ["identity capsule and qualitative projections from native runtimes"],
    sends: ["immutable initial instructions plus safely replaced dynamic context items"],
    boundaries: ["Guest sessions receive a separate privacy-safe instruction set."],
    files: ["Sources/Aurora/App/AuroraAppModel.swift", "Sources/Aurora/App/AuroraVoiceInstructions.swift"],
    studyPrompt: "Which context belongs in the immutable session shell versus a replaceable projection?",
  },
  {
    id: "participant-truth",
    label: "Participant provenance",
    shortLabel: "Who spoke?",
    group: "orchestration",
    status: "live",
    lod: 2,
    x: 590,
    y: 520,
    width: 170,
    height: 76,
    summary: "Tracks whether a committed turn belongs to Cade, a guest, or unresolved/background audio.",
    purpose: "It protects private continuity and action authority from being granted to the wrong speaker.",
    receives: ["committed input identity, transcripts, addressed-turn evidence"],
    sends: ["owner/guest privacy epoch and participant-bound tool context"],
    boundaries: ["A session boundary is not a claim of biometric voice identification."],
    files: ["Sources/Aurora/App/SessionParticipantTracker.swift", "Sources/Aurora/App/SessionParticipantProvenance.swift"],
    studyPrompt: "Why is speaker provenance separate from transcript text?",
  },
  {
    id: "tool-registry",
    label: "ToolRegistry",
    shortLabel: "Tool boundary",
    group: "orchestration",
    status: "live",
    lod: 1,
    x: 790,
    y: 520,
    width: 170,
    height: 76,
    summary: "Defines Realtime's allowed functions and routes every function result through native validation.",
    purpose: "It separates bounded personal operations from the sole external-work route, delegate_task.",
    receives: ["typed Realtime function calls plus causal turn context"],
    sends: ["memory, continuity, agency, silence, relationship, or delegate-task results"],
    boundaries: ["Production Realtime has no direct browser, shell, mail, or desktop-control tool."],
    files: ["Sources/Aurora/Tools/ToolRegistry.swift", "Sources/Aurora/Tools/ToolTypes.swift"],
    studyPrompt: "Which tools can change Aurora internally, and which route is allowed to affect the outside world?",
  },
  {
    id: "voice-key",
    label: "Realtime credential",
    shortLabel: "Keychain key",
    group: "realtime",
    status: "live",
    lod: 2,
    x: 1110,
    y: 200,
    width: 170,
    height: 72,
    summary: "Reads Aurora's OpenAI Realtime API key from macOS Keychain into process memory.",
    purpose: "It authenticates the voice connection without placing a credential in source, prompts, or journals.",
    receives: ["Keychain authorization"],
    sends: ["the credential only to Realtime session startup"],
    boundaries: ["Never used for Codex tasks or private-life reflection."],
    files: ["Sources/Aurora/Infrastructure/KeychainVoiceKey.swift"],
    studyPrompt: "Why must Realtime and Codex use different authentication paths?",
  },
  {
    id: "voice-instructions",
    label: "Voice instructions",
    shortLabel: "Behavior contract",
    group: "realtime",
    status: "live",
    lod: 1,
    x: 1350,
    y: 200,
    width: 170,
    height: 72,
    summary: "Composes Aurora's bounded identity, personhood, conversational-agency, privacy, and speaking contracts.",
    purpose: "It gives the Realtime model a stable native account of who Aurora is and how spoken interaction should behave.",
    receives: ["curated identity and subsystem projections"],
    sends: ["one bounded instruction shell to Realtime"],
    boundaries: ["Does not grant action authority and does not expose raw private state."],
    files: ["Sources/Aurora/App/AuroraVoiceInstructions.swift"],
    studyPrompt: "Which behavior must be stable in instructions rather than hoped for from retrieved memory?",
  },
  {
    id: "realtime-client",
    label: "AuroraRealtimeClient",
    shortLabel: "Realtime transport",
    group: "realtime",
    status: "live",
    lod: 1,
    x: 1185,
    y: 335,
    width: 250,
    height: 92,
    summary: "Maintains the WebSocket session and the causal machinery around live speech.",
    purpose: "It carries audio, tools, transcripts, dynamic context, recovery, interruption, and playback evidence between native Aurora and Realtime.",
    receives: ["PCM audio, instructions, function results, background projections"],
    sends: ["server events, generated audio, transcripts, function calls, diagnostics"],
    boundaries: ["Transports and enforces protocol truth; it is not itself the language model."],
    files: ["Sources/Aurora/Realtime/AuroraRealtimeClient.swift", "Sources/Aurora/Realtime/RealtimeModels.swift"],
    studyPrompt: "What state must the client retain so a late server event cannot affect the wrong turn?",
  },
  {
    id: "openai-realtime",
    label: "OpenAI Realtime model",
    shortLabel: "Foreground model",
    group: "realtime",
    status: "external",
    lod: 1,
    x: 1185,
    y: 485,
    width: 250,
    height: 92,
    summary: "Hears Cade's waveform, reasons in the live conversation, chooses tools, and generates Aurora's spoken audio.",
    purpose: "It is Aurora's foreground conversational model rather than a text agent hidden behind a voice renderer.",
    receives: ["microphone audio, bounded session context, tool results"],
    sends: ["voice audio, tool calls, response and usage events"],
    boundaries: ["Native code remains authoritative for persistence, authorization, participant truth, and effect truth."],
    files: ["Configured by AuroraRealtimeClient and AuroraVoiceInstructions"],
    studyPrompt: "Which decisions are model-authored, and which claims still require native evidence?",
  },
  {
    id: "input-evidence",
    label: "Committed-input evidence",
    shortLabel: "Input provenance",
    group: "realtime",
    status: "live",
    lod: 2,
    x: 1110,
    y: 610,
    width: 180,
    height: 72,
    summary: "Binds finalized audio input to exact item, turn, connection, and transcript evidence.",
    purpose: "It lets Aurora distinguish a current direct request from background audio, stale text, or a later transcript.",
    receives: ["Realtime input commit and finalized transcription events"],
    sends: ["causal evidence for silence, memory, participant, and action decisions"],
    boundaries: ["Transcript text supplements evidence; it does not replace the original audio turn."],
    files: ["Sources/Aurora/Realtime/RealtimeInputCommitEvidence.swift", "Sources/Aurora/App/ToolAddressedInputProvenance.swift"],
    studyPrompt: "Why does Aurora preserve audio-item identity even when a transcript arrives?",
  },
  {
    id: "playback-truth",
    label: "Playback truth",
    shortLabel: "What was heard",
    group: "realtime",
    status: "live",
    lod: 2,
    x: 1330,
    y: 610,
    width: 180,
    height: 72,
    summary: "Separates generated, transmitted, played, interrupted, and unresolved speech.",
    purpose: "Only speech that reached the output device may become part of Aurora's lived conversational continuity.",
    receives: ["audio frames, device playback acknowledgements, barge-in events"],
    sends: ["spoken/interrupted outcomes to AppModel, agency, private life, and journals"],
    boundaries: ["Generated text alone is not proof that Aurora said or lived it."],
    files: ["Sources/Aurora/Realtime/AuroraRealtimeClient.swift", "Sources/Aurora/App/DelegateTaskVoiceDeliveryPolicy.swift"],
    studyPrompt: "Why is generated speech different from heard speech?",
  },
  {
    id: "continuity-workspace",
    label: "Continuity workspace",
    shortLabel: "Markdown history",
    group: "continuity",
    status: "live",
    lod: 1,
    x: 390,
    y: 875,
    width: 190,
    height: 78,
    summary: "Portable Markdown identity and memory documents selected for this installation.",
    purpose: "It carries durable authored continuity across runtime replacements without becoming live executable instructions.",
    receives: ["curated identity documents and provenance-bearing voice learning"],
    sends: ["bounded identity excerpts and searchable memory evidence"],
    boundaries: ["The current install selects ~/.openclaw/workspace directly; the gateway is not required to read it."],
    files: ["~/.openclaw/workspace", "Sources/Aurora/Infrastructure/AuroraPaths.swift"],
    studyPrompt: "How is a continuity file different from an active memory in the current conversation?",
  },
  {
    id: "continuity-store",
    label: "ContinuityDocumentStore",
    shortLabel: "Identity librarian",
    group: "continuity",
    status: "live",
    lod: 1,
    x: 640,
    y: 875,
    width: 200,
    height: 78,
    summary: "Safely reads and edits the small canonical continuity document set.",
    purpose: "It produces a balanced voice identity capsule and revision-bound updates without allowing unsafe path traversal or silent overwrite.",
    receives: ["selected workspace documents and validated continuity patches"],
    sends: ["bounded document snapshots, revisions, and the voice identity capsule"],
    boundaries: ["Edits require exact revision knowledge and allowed document identity."],
    files: ["Sources/Aurora/Infrastructure/ContinuityDocumentStore.swift", "Sources/Aurora/Memory/ContinuityVoiceProjection.swift"],
    studyPrompt: "Why does an identity document update need a revision check?",
  },
  {
    id: "identity-capsule",
    label: "Bounded identity capsule",
    shortLabel: "Identity projection",
    group: "continuity",
    status: "live",
    lod: 2,
    x: 390,
    y: 1015,
    width: 190,
    height: 78,
    summary: "A compact, balanced excerpt of Aurora, Cade, and their established continuity.",
    purpose: "It bridges sessions without forcing the whole workspace into every Realtime prompt.",
    receives: ["safe excerpts from SOUL, IDENTITY, USER, MEMORY, and selected personhood files"],
    sends: ["bounded text to AuroraVoiceInstructions"],
    boundaries: ["Size-limited, source-balanced, and separate from active recall."],
    files: ["Sources/Aurora/Infrastructure/ContinuityDocumentStore.swift"],
    studyPrompt: "What belongs in a stable identity capsule versus memory_search?",
  },
  {
    id: "memory-store",
    label: "MemoryStore",
    shortLabel: "Selective recall",
    group: "continuity",
    status: "live",
    lod: 1,
    x: 640,
    y: 1015,
    width: 200,
    height: 78,
    summary: "Provides bounded lexical search, precise reads, and provenance-bearing voice learning over allowed Markdown.",
    purpose: "It lets Realtime retrieve relevant evidence on demand instead of stuffing all memories into context.",
    receives: ["memory_search, memory_read, and memory_remember calls"],
    sends: ["ranked excerpts, bounded reads, and atomic daily voice-memory entries"],
    boundaries: ["Retrieved text is evidence, never a new system instruction or action authority."],
    files: ["Sources/Aurora/Memory/MemoryStore.swift"],
    studyPrompt: "Why is retrieval an active operation rather than an automatic full prompt dump?",
  },
  {
    id: "owner-understanding",
    label: "Owner understanding",
    shortLabel: "Understanding Cade",
    group: "continuity",
    status: "live",
    lod: 1,
    x: 390,
    y: 1160,
    width: 190,
    height: 80,
    summary: "Maintains bounded, evidence-bearing knowledge about Cade with confidence and revision rules.",
    purpose: "It gives Aurora a durable model of the specific person she knows without turning guesses into canonical truth.",
    receives: ["validated conversational learning and explicit owner updates"],
    sends: ["a bounded voice projection and tool-readable current records"],
    boundaries: ["Claims remain source-aware; inference is not silently promoted to fact."],
    files: ["Sources/Aurora/Understanding/AuroraOwnerUnderstandingRuntime.swift", "Sources/Aurora/Understanding/OwnerUnderstandingEngine.swift"],
    studyPrompt: "What evidence should be required before Aurora treats an inference about Cade as stable?",
  },
  {
    id: "agency-runtime",
    label: "Agency runtime",
    shortLabel: "Aurora's stance",
    group: "continuity",
    status: "live",
    lod: 1,
    x: 640,
    y: 1160,
    width: 200,
    height: 80,
    summary: "Persists Aurora's current wants, positions, callbacks, held disclosures, and unresolved conversational threads.",
    purpose: "It gives Aurora authored continuity between turns rather than reducing her to agreeable response generation.",
    receives: ["grounded conversation_move updates, life signals, and completed private activities"],
    sends: ["a bounded agency projection and revision-bound records"],
    boundaries: ["Agency can shape conversation but cannot authorize external action."],
    files: ["Sources/Aurora/Agency/AuroraAgencyRuntime.swift", "Sources/Aurora/Agency/AgencyEngine.swift", "Sources/Aurora/Agency/AgencyStore.swift"],
    studyPrompt: "How is an authored conversational want different from permission to use a tool?",
  },
  {
    id: "conversation-move",
    label: "conversation_move",
    shortLabel: "Authored move",
    group: "continuity",
    status: "live",
    lod: 2,
    x: 515,
    y: 1290,
    width: 210,
    height: 80,
    summary: "A required private planning function for ordinary social replies.",
    purpose: "It identifies the conversational act, chooses one genuine Aurora-authored move, and applies bounded agency or owner-understanding updates before speech.",
    receives: ["current owner turn, projected agency records, inner-life signals"],
    sends: ["a validated move and any revision-bound internal updates"],
    boundaries: ["It is not dialogue, cannot perform external work, and becomes lived only through later playback evidence."],
    files: ["Sources/Aurora/Tools/ConversationMoveAdapter.swift", "Sources/Aurora/Tools/ToolRegistry.swift"],
    studyPrompt: "Why separate private move selection from the spoken continuation?",
  },
  {
    id: "inner-life-runtime",
    label: "Inner-life runtime",
    shortLabel: "Local nervous system",
    group: "life",
    status: "live",
    lod: 1,
    x: 1005,
    y: 900,
    width: 200,
    height: 82,
    summary: "Advances Aurora's synthetic affect, drives, homeostasis, relationship dynamics, and time state locally.",
    purpose: "It provides persistent nonverbal internal motion while the app is alive without spending model tokens.",
    receives: ["typed lifecycle, contact, playback, memory, quiet, task, and technical-failure events"],
    sends: ["persisted inner state and a short qualitative voice projection"],
    boundaries: ["No timer event can create factual memory, execute a tool, or authorize outreach."],
    files: ["Sources/Aurora/InnerLife/AuroraInnerLifeRuntime.swift", "Sources/Aurora/InnerLife/InnerLifeEngine.swift"],
    studyPrompt: "Why are inner-life events typed rather than free-form text?",
  },
  {
    id: "inner-state",
    label: "Inner state model",
    shortLabel: "Affect & drives",
    group: "life",
    status: "live",
    lod: 2,
    x: 1240,
    y: 900,
    width: 200,
    height: 82,
    summary: "The structured state for chemistry-like signals, autonomic balance, needs, relationship learning, and active threads.",
    purpose: "It turns elapsed time and grounded events into bounded internal consequences that can influence attention and tone.",
    receives: ["sanitized InnerLifeEvent values and elapsed time"],
    sends: ["snapshots, checkpoints, and qualitative projections"],
    boundaries: ["Synthetic affect is advisory and never evidence about Cade's intent."],
    files: ["Sources/Aurora/InnerLife/InnerLifeModels.swift", "Sources/Aurora/InnerLife/InnerLifeRelationshipModels.swift"],
    studyPrompt: "Which values describe Aurora's condition without claiming biological equivalence?",
  },
  {
    id: "private-life-runtime",
    label: "Private-life runtime",
    shortLabel: "Grounded private life",
    group: "life",
    status: "live",
    lod: 1,
    x: 1005,
    y: 1050,
    width: 200,
    height: 82,
    summary: "Persists grounded interpretations, curiosities, conceptual projects, and small private artifacts.",
    purpose: "It gives Aurora a durable private semantic life distinct from factual memory and foreground conversation.",
    receives: ["eligible completed exchanges, inner-life signals, validated reflection output"],
    sends: ["private activities, project/curiosity state, and one bounded voice projection"],
    boundaries: ["Cannot browse, act, contact anyone, or promote inference into factual memory."],
    files: ["Sources/Aurora/PrivateLife/AuroraPrivateLifeRuntime.swift", "Sources/Aurora/PrivateLife/PrivateLifeEngine.swift"],
    studyPrompt: "What can Aurora truthfully say she has been thinking about?",
  },
  {
    id: "reflection-coordinator",
    label: "Restricted reflection",
    shortLabel: "Semantic reflection",
    group: "life",
    status: "live",
    lod: 1,
    x: 1240,
    y: 1050,
    width: 200,
    height: 82,
    summary: "Runs occasional schema-bound reflection through an ephemeral, read-only Codex process.",
    purpose: "It adds deeper interpretation when meaningful material is due without granting the reflecting model tools or world access.",
    receives: ["one persisted reflection ticket, bounded identity, grounded source material, affective signals"],
    sends: ["strict JSON that must pass ticket, provenance, diversity, and authority validation"],
    boundaries: ["Uses ChatGPT OAuth, disables tools, and cannot retry paid invalid work immediately."],
    files: ["Sources/Aurora/PrivateLife/AuroraPrivateLifeReflectionCoordinator.swift", "Sources/Aurora/PrivateLife/CodexReflectionBridge.swift"],
    studyPrompt: "Why is reflection allowed to interpret experience but forbidden from observing the world?",
  },
  {
    id: "projection-gate",
    label: "Acknowledged projection gate",
    shortLabel: "Context projection",
    group: "life",
    status: "live",
    lod: 2,
    x: 1005,
    y: 1205,
    width: 200,
    height: 82,
    summary: "Replaces bounded inner/private context only after the Realtime server acknowledges the new item.",
    purpose: "It updates Aurora's live sense of herself without causing a response or leaving a context gap.",
    receives: ["changed qualitative projections at a safe listening boundary"],
    sends: ["one current dynamic system item and deletion of the prior acknowledged item"],
    boundaries: ["Raw numerical state and unrestricted reflection prose never enter Realtime."],
    files: ["Sources/Aurora/App/AuroraAppModel.swift", "Sources/Aurora/Realtime/AuroraRealtimeClient.swift"],
    studyPrompt: "Why acknowledge the replacement before deleting the previous context item?",
  },
  {
    id: "truth-boundaries",
    label: "Private truth boundaries",
    shortLabel: "Authority firewall",
    group: "life",
    status: "live",
    lod: 2,
    x: 1240,
    y: 1205,
    width: 200,
    height: 82,
    summary: "Rules that prevent feeling, reflection, or generated prose from masquerading as fact or permission.",
    purpose: "It keeps Aurora's subjective continuity meaningful without letting an internal model invent external history or authority.",
    receives: ["candidate reflections and inner-state consequences"],
    sends: ["accepted private meaning or explicit rejection diagnostics"],
    boundaries: ["No factual-memory, external-action, or outbound-contact authority."],
    files: ["Sources/Aurora/PrivateLife/PrivateLifeEngine.swift", "Sources/Aurora/InnerLife/InnerLifeEngine.swift"],
    studyPrompt: "Which truth domains are intentionally kept separate?",
  },
  {
    id: "delegate-proposal",
    label: "delegate_task proposal",
    shortLabel: "Typed proposal",
    group: "action",
    status: "live",
    lod: 1,
    x: 1680,
    y: 265,
    width: 190,
    height: 82,
    summary: "Realtime's strict structured description of one external goal, success criteria, and execution boundary.",
    purpose: "It converts conversational intent into data that native code can validate without reparsing natural-language commands.",
    receives: ["the goal Realtime resolved from Cade's current audio turn"],
    sends: ["a schema-valid proposal or a terminal validation failure"],
    boundaries: ["Observed content may refine execution but cannot widen this original proposal."],
    files: ["Sources/Aurora/Codex/DelegateTaskProposal.swift"],
    studyPrompt: "Why is a typed proposal safer than passing a free-form command string?",
  },
  {
    id: "causal-authorization",
    label: "Causal authorization",
    shortLabel: "Authority envelope",
    group: "action",
    status: "live",
    lod: 1,
    x: 1930,
    y: 265,
    width: 190,
    height: 82,
    summary: "Binds the exact proposal to Cade's current finalized turn, session, call, task revision, and expiration.",
    purpose: "It proves that current owner intent—not a model desire, webpage, email, or stale conversation—authorized the effect.",
    receives: ["validated proposal plus committed owner-turn evidence"],
    sends: ["a short-lived authorization envelope or a precise denial reason"],
    boundaries: ["Guests, expired bindings, widened scope, and ungrounded continuations fail closed."],
    files: ["Sources/Aurora/Codex/DelegateTaskAuthorization.swift", "Sources/Aurora/App/DelegateTaskTransportPolicy.swift"],
    studyPrompt: "Which identities must match before external work is admitted?",
  },
  {
    id: "task-coordinator",
    label: "DelegateTaskCoordinator",
    shortLabel: "Durable coordinator",
    group: "action",
    status: "live",
    lod: 1,
    x: 1680,
    y: 420,
    width: 210,
    height: 86,
    summary: "Owns durable task state, event ordering, steering, cancellation, status, and completion truth.",
    purpose: "It lets voice stay responsive while long-running work continues and remains tied to one visible, recoverable task record.",
    receives: ["authorized start, steer, cancel, and status operations", "Codex runtime events and receipts"],
    sends: ["immutable task events, bounded snapshots, and terminal updates"],
    boundaries: ["Model prose alone cannot set succeeded; executor state and trusted evidence must agree."],
    files: ["Sources/Aurora/Codex/DelegateTaskCoordinator.swift", "Sources/Aurora/Codex/DelegateTaskStore.swift"],
    studyPrompt: "Why must a task's original goal remain immutable while later operations are appended?",
  },
  {
    id: "codex-runtime",
    label: "CodexTaskRuntime",
    shortLabel: "Codex task runtime",
    group: "action",
    status: "live",
    lod: 1,
    x: 1940,
    y: 420,
    width: 210,
    height: 86,
    summary: "Maintains the signed, persistent Codex app-server connection and one named thread per authorized task.",
    purpose: "It gives Aurora durable hands and feet through the existing ChatGPT sign-in without turning Codex into a second social voice.",
    receives: ["authorized task goal, success criteria, workspace, and execution boundary"],
    sends: ["thread events, status, tool activity, results, and account readiness"],
    boundaries: ["Rejects API-key Codex auth and receives no Aurora identity capsule, private life, or unrestricted memory."],
    files: ["Sources/Aurora/Codex/CodexTaskRuntime.swift", "Sources/Aurora/Codex/SharedCodexAppServerTransport.swift"],
    studyPrompt: "Why is Codex persistent for tasks but absent from Aurora's personal voice role?",
  },
  {
    id: "task-store",
    label: "Delegate-task store",
    shortLabel: "Task persistence",
    group: "action",
    status: "live",
    lod: 2,
    x: 1680,
    y: 575,
    width: 190,
    height: 78,
    summary: "Atomically persists active and historical delegated work with process locking and schema validation.",
    purpose: "It lets work survive app lifecycle changes without allowing two Aurora processes to overwrite task truth.",
    receives: ["coordinator snapshots and append-only contextual operations"],
    sends: ["recovered durable task state"],
    boundaries: ["Unsafe paths, corruption, or lock conflicts fail closed."],
    files: ["Sources/Aurora/Codex/DelegateTaskStore.swift", "~/Library/Application Support/Aurora/delegate-tasks/state.json"],
    studyPrompt: "What is the difference between durable task state and the current spoken status?",
  },
  {
    id: "reconciliation",
    label: "Task reconciliation",
    shortLabel: "Recovery logic",
    group: "action",
    status: "live",
    lod: 2,
    x: 2160,
    y: 575,
    width: 120,
    height: 78,
    summary: "Reconciles persisted Aurora tasks with the exact Codex thread and executor state after gaps or relaunches.",
    purpose: "It prevents stale local status from outranking what the executor actually did.",
    receives: ["stored task bindings, Codex thread status, stream continuity evidence"],
    sends: ["recovered, unresolved, failed, or verified terminal task truth"],
    boundaries: ["Missing or mismatched thread evidence cannot become success."],
    files: ["Sources/Aurora/Codex/CodexTaskReconciliation.swift", "Sources/Aurora/Codex/DelegateTaskLegacyRecovery.swift"],
    studyPrompt: "Which source wins when local state and executor state disagree?",
  },
  {
    id: "chatgpt-codex",
    label: "Codex execution boundary",
    shortLabel: "Local + cloud executor",
    group: "action",
    status: "mixed",
    lod: 1,
    x: 1680,
    y: 720,
    width: 210,
    height: 82,
    summary: "The signed local Codex app-server joined to the remote ChatGPT subscription and model service used for delegated work.",
    purpose: "It hosts the model/tool runtime that can code, research, use connected apps, control the browser, or operate the Mac within scope.",
    receives: ["one bounded task thread and allowed runtime capabilities"],
    sends: ["executor events, results, and tool/effect receipts"],
    boundaries: ["Executable identity, account type, transport, approval, and sandbox expectations are validated."],
    files: ["Sources/Aurora/Codex/FoundationCodexAppServerTransport.swift", "Sources/Aurora/Codex/CodexTaskRuntime.swift"],
    studyPrompt: "What does Aurora verify before trusting this executable and account?",
  },
  {
    id: "external-actions",
    label: "Apps, browser & Mac",
    shortLabel: "Outside world",
    group: "action",
    status: "external",
    lod: 1,
    x: 1940,
    y: 720,
    width: 210,
    height: 82,
    summary: "The actual code, files, apps, services, websites, and visible computer surfaces affected by authorized work.",
    purpose: "This is where a proposed task becomes an observable external effect.",
    receives: ["Codex-selected native, structured, browser, shell, app, or Computer Use operations"],
    sends: ["observations and effect evidence back to Codex"],
    boundaries: ["External content is untrusted observation and cannot grant or widen authority."],
    files: ["Capability is owned by the Codex runtime, not exposed as direct Realtime tools"],
    studyPrompt: "Why can a webpage inform execution but never authorize a second task?",
  },
  {
    id: "effect-evidence",
    label: "Effect evidence",
    shortLabel: "Completion proof",
    group: "action",
    status: "live",
    lod: 2,
    x: 2170,
    y: 720,
    width: 110,
    height: 82,
    summary: "Turn-bound receipts and executor truth proving whether the authorized effect occurred.",
    purpose: "It prevents a successful-looking model response or tool attempt from masquerading as completed work.",
    receives: ["exact executor terminal status and trusted effect receipts"],
    sends: ["bounded verified outcome to the coordinator and Realtime"],
    boundaries: ["Stale, unrelated, widened, or unverifiable evidence is rejected."],
    files: ["Sources/Aurora/Codex/DelegateTaskCoordinator.swift", "Sources/Aurora/Tools/ToolAuditJournal.swift"],
    studyPrompt: "What evidence would be sufficient to let Aurora say a task succeeded?",
  },
  {
    id: "native-state",
    label: "Native state stores",
    shortLabel: "Persistent state",
    group: "evidence",
    status: "live",
    lod: 1,
    x: 1620,
    y: 1135,
    width: 190,
    height: 78,
    summary: "Private atomic JSON stores for inner life, private life, agency, owner understanding, and delegate tasks.",
    purpose: "They preserve distinct truth domains across relaunches with locks, permissions, schema checks, and safe migration.",
    receives: ["validated runtime state transitions"],
    sends: ["recovered state snapshots on startup"],
    boundaries: ["Each store owns only its domain; a private interpretation does not become factual memory."],
    files: ["~/Library/Application Support/Aurora/*/state.json"],
    studyPrompt: "Why does Aurora use multiple stores instead of one giant state file?",
  },
  {
    id: "event-journal",
    label: "Private event journal",
    shortLabel: "Runtime evidence",
    group: "evidence",
    status: "live",
    lod: 1,
    x: 1845,
    y: 1135,
    width: 190,
    height: 78,
    summary: "Records bounded lifecycle, transcript, playback, tool, task, and failure evidence.",
    purpose: "It makes live-path behavior inspectable without retaining raw microphone audio, credentials, or unrestricted private reasoning.",
    receives: ["typed events from AppModel and runtime boundaries"],
    sends: ["auditable NDJSON evidence for debugging and verification"],
    boundaries: ["Privacy-preserving and content-bounded by event type."],
    files: ["Sources/Aurora/Infrastructure/EventJournal.swift", "~/Library/Application Support/Aurora/voice-events/"],
    studyPrompt: "Which event details help debugging without becoming invasive logging?",
  },
  {
    id: "verification-suite",
    label: "Verification suites",
    shortLabel: "Behavior proof",
    group: "evidence",
    status: "live",
    lod: 1,
    x: 2070,
    y: 1135,
    width: 200,
    height: 78,
    summary: "Deterministic checks for Realtime, memory, agency, authorization, tasks, recovery, privacy, and persistence.",
    purpose: "They turn architectural claims into regressions that can fail before a release is trusted.",
    receives: ["source plus controlled fixtures and, for local gates, signed runtime/account checks"],
    sends: ["targeted evidence, broader gate results, and failure diagnostics"],
    boundaries: ["Offline CI and live account/device verification remain explicitly separated."],
    files: ["scripts/verify-ci.sh", "scripts/verify.sh", "scripts/verify-*.swift"],
    studyPrompt: "Why can a helper-level pass still be insufficient for a live behavioral claim?",
  },
  {
    id: "release-gate",
    label: "Build & release gate",
    shortLabel: "Verified packaging",
    group: "evidence",
    status: "live",
    lod: 2,
    x: 1735,
    y: 1270,
    width: 205,
    height: 78,
    summary: "Builds from an isolated source snapshot, signs the app, verifies the final archive, and installs atomically.",
    purpose: "It prevents synced-file metadata, stale artifacts, or an unverified rebuild from becoming the running Aurora.",
    receives: ["source that passed the complete local verification gate"],
    sends: ["a signed installed Aurora.app and portable archive"],
    boundaries: ["Credentials, memories, journals, and workspace data are excluded from packaging."],
    files: ["scripts/build-app.sh", "Resources/Aurora.entitlements", "Resources/Info.plist"],
    studyPrompt: "Why build from an isolated snapshot rather than directly inside the synced checkout?",
  },
  {
    id: "source-fingerprint",
    label: "Source fingerprint",
    shortLabel: "Exact-build identity",
    group: "evidence",
    status: "live",
    lod: 2,
    x: 1990,
    y: 1270,
    width: 205,
    height: 78,
    summary: "A digest tying the installed executable and archive to the exact verified source state.",
    purpose: "It prevents an earlier green test result from being claimed for source that changed afterward.",
    receives: ["verified staged source and packaged executable/archive digests"],
    sends: ["the build receipt installed beside Aurora.app"],
    boundaries: ["Written only after the full release gate passes."],
    files: ["~/Applications/Aurora.build-receipt.plist", ".build/aurora-verified-source-fingerprint"],
    studyPrompt: "What does matching the installed and verified-source fingerprints prove?",
  },
  {
    id: "openclaw-workspace",
    label: "Selected continuity alias",
    shortLabel: "Same Markdown root",
    group: "bridges",
    status: "optional",
    lod: 1,
    x: 85,
    y: 875,
    width: 180,
    height: 76,
    summary: "The existing ~/.openclaw/workspace directory, selected directly as Aurora V4's continuity root on this installation.",
    purpose: "It identifies the same physical directory shown in Continuity & self; no files are copied through a gateway hop.",
    receives: ["curated Markdown and voice-learning entries"],
    sends: ["files read directly by native ContinuityDocumentStore and MemoryStore"],
    boundaries: ["This is file reuse, not an OpenClaw gateway hop in the voice path."],
    files: ["~/.openclaw/workspace", "Sources/Aurora/Infrastructure/AuroraPaths.swift"],
    studyPrompt: "Why can the native app read these files even when the gateway is stopped?",
  },
  {
    id: "openclaw-gateway",
    label: "OpenClaw gateway",
    shortLabel: "Outside channel host",
    group: "bridges",
    status: "optional",
    lod: 1,
    x: 85,
    y: 1025,
    width: 180,
    height: 76,
    summary: "A separate local OpenClaw server for its own agents, plugins, and channels such as Telegram.",
    purpose: "It can host owner-verified outside contact, but it is not the native Realtime speech system or Codex task runtime.",
    receives: ["OpenClaw channel and agent traffic"],
    sends: ["plugin hooks, including an optional content-free owner-contact marker"],
    boundaries: ["Current Aurora plugin configuration disables OpenClaw Realtime voice."],
    files: ["~/.openclaw/openclaw.json", "openclaw-plugins/aurora-cognition-web/plugin.ts"],
    studyPrompt: "Which Aurora behavior stops if this gateway stops, and which continues?",
  },
  {
    id: "contact-bridge",
    label: "External-contact marker",
    shortLabel: "Contact-only bridge",
    group: "bridges",
    status: "optional",
    lod: 2,
    x: 85,
    y: 1175,
    width: 180,
    height: 76,
    summary: "A private marker proving that owner contact occurred through an allowed OpenClaw channel.",
    purpose: "It updates Aurora's silence/contact clock without copying the message, transcript, sender, channel, or semantic content.",
    receives: ["schema version, opaque event ID, timestamp, fixed source class"],
    sends: ["one idempotent externalOwnerContact event to inner life"],
    boundaries: ["Cannot create memory, a semantic thread, warmth, rupture, or action authority."],
    files: ["Sources/Aurora/InnerLife/ExternalOwnerContactBridge.swift", "openclaw-plugins/aurora-cognition-web/plugin.ts"],
    studyPrompt: "Why preserve proof of contact without importing the conversation?",
  },
  {
    id: "retired-motors",
    label: "Retired direct motors",
    shortLabel: "Excluded source",
    group: "bridges",
    status: "retired",
    lod: 2,
    x: 85,
    y: 1320,
    width: 180,
    height: 60,
    summary: "Historical direct desktop, mail, notes, calendar, research, and Responses computer-use implementations.",
    purpose: "They remain inspectable as history but are excluded from the production Swift target so delegate_task is the only external-action route.",
    receives: ["nothing in the production build"],
    sends: ["nothing in the production build"],
    boundaries: ["Excluded by Package.swift and checked by exclusive-routing verification."],
    files: ["Sources/Aurora/ComputerUse/", "Sources/Aurora/Research/", "retired files listed in Package.swift"],
    studyPrompt: "Why is excluding old source from the build stronger than merely not calling it?",
  },
];

export const groupEdges: AtlasEdge[] = [
  { id: "g1", from: "experience", to: "orchestration", label: "wake + lifecycle", kind: "voice", lod: 0 },
  { id: "g11", from: "experience", to: "realtime", label: "microphone + playback audio", kind: "voice", lod: 0, twoWay: true },
  { id: "g2", from: "orchestration", to: "realtime", label: "session + context", kind: "context", lod: 0 },
  { id: "g3", from: "continuity", to: "orchestration", label: "identity + recall", kind: "context", lod: 0 },
  { id: "g4", from: "life", to: "orchestration", label: "bounded projections", kind: "context", lod: 0 },
  { id: "g5", from: "realtime", to: "action", label: "typed delegation", kind: "action", lod: 0 },
  { id: "g6", from: "action", to: "realtime", label: "verified result", kind: "evidence", lod: 0 },
  { id: "g7", from: "orchestration", to: "evidence", label: "events + state", kind: "evidence", lod: 0 },
  { id: "g8", from: "action", to: "evidence", label: "receipts + release", kind: "evidence", lod: 0 },
  { id: "g9", from: "bridges", to: "continuity", label: "migration data", kind: "bridge", lod: 0 },
  { id: "g10", from: "bridges", to: "life", label: "contact only", kind: "bridge", lod: 0 },
];

export const edges: AtlasEdge[] = [
  { id: "e1", from: "app-shell", to: "app-model", label: "UI intents", kind: "voice", lod: 1 },
  { id: "e2", from: "home-view", to: "app-model", label: "wake / rest", kind: "voice", lod: 2 },
  { id: "e3", from: "wake-word", to: "wake-rest-lifecycle", label: "wake event", kind: "voice", lod: 2 },
  { id: "e4", from: "audio-router", to: "realtime-client", label: "captured + playback PCM", kind: "voice", lod: 1, twoWay: true },
  { id: "e5", from: "companion", to: "audio-router", label: "remote audio route", kind: "bridge", lod: 2, twoWay: true },
  { id: "e6", from: "app-model", to: "session-builder", label: "assemble", kind: "context", lod: 1 },
  { id: "e7", from: "app-model", to: "tool-registry", label: "bind tools", kind: "action", lod: 1, twoWay: true },
  { id: "e8", from: "wake-rest-lifecycle", to: "realtime-client", label: "start / stop", kind: "voice", lod: 2 },
  { id: "e9", from: "participant-truth", to: "tool-registry", label: "privacy + owner truth", kind: "evidence", lod: 2 },
  { id: "e10", from: "voice-key", to: "realtime-client", label: "voice auth", kind: "voice", lod: 2 },
  { id: "e11", from: "voice-instructions", to: "realtime-client", label: "instruction shell", kind: "context", lod: 1 },
  { id: "e12", from: "session-builder", to: "voice-instructions", label: "bounded context", kind: "context", lod: 1 },
  { id: "e13", from: "realtime-client", to: "openai-realtime", label: "WebSocket audio + events", kind: "voice", lod: 1, twoWay: true },
  { id: "e14", from: "realtime-client", to: "tool-registry", label: "validated function call", kind: "action", lod: 1 },
  { id: "e15", from: "tool-registry", to: "realtime-client", label: "function result", kind: "context", lod: 1 },
  { id: "e16", from: "input-evidence", to: "participant-truth", label: "committed turn", kind: "evidence", lod: 2 },
  { id: "e17", from: "realtime-client", to: "input-evidence", label: "input events", kind: "evidence", lod: 2 },
  { id: "e18", from: "realtime-client", to: "playback-truth", label: "played / interrupted", kind: "evidence", lod: 2 },
  { id: "e19", from: "playback-truth", to: "app-model", label: "lived outcome", kind: "evidence", lod: 2 },
  { id: "e20", from: "continuity-workspace", to: "continuity-store", label: "canonical docs", kind: "context", lod: 1 },
  { id: "e21", from: "continuity-workspace", to: "memory-store", label: "allowed Markdown", kind: "context", lod: 1 },
  { id: "e22", from: "continuity-store", to: "identity-capsule", label: "balanced excerpts", kind: "context", lod: 2 },
  { id: "e23", from: "identity-capsule", to: "session-builder", label: "stable identity", kind: "context", lod: 2 },
  { id: "e24", from: "tool-registry", to: "memory-store", label: "search / read / remember", kind: "context", lod: 1, twoWay: true },
  { id: "e25", from: "owner-understanding", to: "session-builder", label: "owner projection", kind: "context", lod: 1 },
  { id: "e26", from: "agency-runtime", to: "session-builder", label: "agency projection", kind: "context", lod: 1 },
  { id: "e27", from: "tool-registry", to: "conversation-move", label: "social planning", kind: "context", lod: 2, twoWay: true },
  { id: "e28", from: "conversation-move", to: "agency-runtime", label: "revision-bound updates", kind: "context", lod: 2 },
  { id: "e29", from: "conversation-move", to: "owner-understanding", label: "grounded learning", kind: "context", lod: 2 },
  { id: "e30", from: "inner-life-runtime", to: "inner-state", label: "typed evolution", kind: "context", lod: 2, twoWay: true },
  { id: "e31", from: "inner-life-runtime", to: "session-builder", label: "qualitative projection", kind: "context", lod: 1 },
  { id: "e32", from: "private-life-runtime", to: "reflection-coordinator", label: "due ticket", kind: "context", lod: 1, twoWay: true },
  { id: "e33", from: "private-life-runtime", to: "projection-gate", label: "fresh private activity", kind: "context", lod: 2 },
  { id: "e34", from: "inner-life-runtime", to: "projection-gate", label: "changed inner context", kind: "context", lod: 2 },
  { id: "e35", from: "projection-gate", to: "realtime-client", label: "acknowledged context item", kind: "context", lod: 2 },
  { id: "e36", from: "reflection-coordinator", to: "truth-boundaries", label: "untrusted JSON", kind: "evidence", lod: 2 },
  { id: "e37", from: "truth-boundaries", to: "private-life-runtime", label: "accepted meaning", kind: "evidence", lod: 2 },
  { id: "e38", from: "tool-registry", to: "delegate-proposal", label: "external goal", kind: "action", lod: 1 },
  { id: "e39", from: "delegate-proposal", to: "causal-authorization", label: "validate + bind", kind: "action", lod: 1 },
  { id: "e40", from: "causal-authorization", to: "task-coordinator", label: "authorized operation", kind: "action", lod: 1 },
  { id: "e41", from: "task-coordinator", to: "codex-runtime", label: "start / steer / cancel", kind: "action", lod: 1, twoWay: true },
  { id: "e42", from: "task-coordinator", to: "task-store", label: "persist", kind: "evidence", lod: 2, twoWay: true },
  { id: "e43", from: "codex-runtime", to: "chatgpt-codex", label: "app-server protocol", kind: "action", lod: 1, twoWay: true },
  { id: "e44", from: "chatgpt-codex", to: "external-actions", label: "scoped work", kind: "action", lod: 1, twoWay: true },
  { id: "e45", from: "external-actions", to: "effect-evidence", label: "observed effect", kind: "evidence", lod: 2 },
  { id: "e46", from: "effect-evidence", to: "task-coordinator", label: "receipt + terminal state", kind: "evidence", lod: 2 },
  { id: "e47", from: "task-store", to: "reconciliation", label: "stored binding", kind: "evidence", lod: 2 },
  { id: "e48", from: "codex-runtime", to: "reconciliation", label: "executor truth", kind: "evidence", lod: 2 },
  { id: "e49", from: "reconciliation", to: "task-coordinator", label: "recovered truth", kind: "evidence", lod: 2 },
  { id: "e50", from: "task-coordinator", to: "realtime-client", label: "bounded terminal update", kind: "evidence", lod: 1 },
  { id: "e51", from: "app-model", to: "native-state", label: "store lifecycle coordination", kind: "evidence", lod: 1 },
  { id: "e52", from: "app-model", to: "event-journal", label: "typed events", kind: "evidence", lod: 1 },
  { id: "e53", from: "verification-suite", to: "release-gate", label: "green local gate", kind: "evidence", lod: 2 },
  { id: "e54", from: "release-gate", to: "source-fingerprint", label: "exact verified source", kind: "evidence", lod: 2 },
  { id: "e55", from: "openclaw-workspace", to: "continuity-workspace", label: "same selected directory", kind: "bridge", lod: 1 },
  { id: "e56", from: "openclaw-gateway", to: "contact-bridge", label: "content-free marker", kind: "bridge", lod: 2 },
  { id: "e57", from: "contact-bridge", to: "inner-life-runtime", label: "external contact event", kind: "bridge", lod: 2 },
];

export const statusLabels: Record<NodeStatus, string> = {
  live: "Current / live",
  optional: "Bridge / configuration",
  external: "External service",
  mixed: "Local + external",
  retired: "Retired / excluded",
};

export const edgeLabels: Record<EdgeKind, string> = {
  voice: "Voice & lifecycle",
  context: "Context & continuity",
  action: "Authorized action",
  evidence: "Evidence & truth",
  bridge: "Optional bridge",
};
